# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gaussian_max_couplingC <- function(mu1, mu2, Sigma1, Sigma2) {
    .Call('_debiasedpmcmc_gaussian_max_couplingC', PACKAGE = 'debiasedpmcmc', mu1, mu2, Sigma1, Sigma2)
}

gaussian_max_coupling_cholesky <- function(mu1, mu2, Cholesky1, Cholesky2, Cholesky_inverse1, Cholesky_inverse2) {
    .Call('_debiasedpmcmc_gaussian_max_coupling_cholesky', PACKAGE = 'debiasedpmcmc', mu1, mu2, Cholesky1, Cholesky2, Cholesky_inverse1, Cholesky_inverse2)
}

estimator_bin <- function(c_chains, component, lower, upper, k, K) {
    .Call('_debiasedpmcmc_estimator_bin', PACKAGE = 'debiasedpmcmc', c_chains, component, lower, upper, k, K)
}

multinomial_resampling_n_ <- function(weights, ndraws) {
    .Call('_debiasedpmcmc_multinomial_resampling_n_', PACKAGE = 'debiasedpmcmc', weights, ndraws)
}

rmvnorm <- function(nsamples, mean, covariance) {
    .Call('_debiasedpmcmc_rmvnorm', PACKAGE = 'debiasedpmcmc', nsamples, mean, covariance)
}

rmvnorm_cholesky <- function(nsamples, mean, cholesky) {
    .Call('_debiasedpmcmc_rmvnorm_cholesky', PACKAGE = 'debiasedpmcmc', nsamples, mean, cholesky)
}

dmvnorm <- function(x, mean, covariance) {
    .Call('_debiasedpmcmc_dmvnorm', PACKAGE = 'debiasedpmcmc', x, mean, covariance)
}

dmvnorm_cholesky_inverse <- function(x, mean, cholesky_inverse) {
    .Call('_debiasedpmcmc_dmvnorm_cholesky_inverse', PACKAGE = 'debiasedpmcmc', x, mean, cholesky_inverse)
}

one_step_pz_vector <- function(xparticles, alphas, t, parameters) {
    .Call('_debiasedpmcmc_one_step_pz_vector', PACKAGE = 'debiasedpmcmc', xparticles, alphas, t, parameters)
}

levydriven_rtrans_ <- function(xparticles, theta, thetatransform) {
    invisible(.Call('_debiasedpmcmc_levydriven_rtrans_', PACKAGE = 'debiasedpmcmc', xparticles, theta, thetatransform))
}

systematic_resampling_n_ <- function(weights, ndraws, u) {
    .Call('_debiasedpmcmc_systematic_resampling_n_', PACKAGE = 'debiasedpmcmc', weights, ndraws, u)
}

